### ISSUE TITLE
Scheduler settings in config files

### ISSUE THREAD

**Issue by ta-kutsuna** [okotaku/diffengine#137]
I have a question about the scheduler setting in DiffEngine configs.

For example, DDPMScheduler is imported and used in 
https://github.com/okotaku/diffengine/blob/main/diffengine/configs/_base_/models/stable_diffusion_v15.py

However, according to the model_index.json of runwayml/stable-diffusion-v1-5
https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/model_index.json
PNDMScheduler is used as the scheduler.

Such a mismatch also happens in other models such as stable diffusion xl.

It is not clear to what extent such differences in schedulers will have an impact, but it would be better to match the model settings on the huggingface.

Thanks for sharing great code!

**Comment by okotaku** [comment]
Thank you for your comments!

The training of diffusion models is typically done using DDPM (Denoising Diffusion Probabilistic Models). During inference, various schedulers are proposed, including DDIM (Denoising Diffusion Implicit Models), and one of them is the PNDMScheduler. These schedulers can be applied to models trained with DDPM, so there should be no issue with the problem you are considering here.

https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py#L557

You can also check diffusers training code that utilizes DDPM.

**Comment by ta-kutsuna** [comment]
I misunderstood that the scheduler used in inference must also be used during training.
Thanks for letting me know!
