### ISSUE TITLE
example notebook will be helpful

### ISSUE THREAD

**Issue by andysingal** [okotaku/diffengine#14]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet
Is it possible to add some notebooks to make the most of your repo. Looking forward to hearing from you.

\[here\]

### Post related information

1. The output of `pip list | grep "mmengine\|diffusers\|transformers\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `diffengine` folder.
   \[here\]

**Comment by okotaku** [comment]
@andysingal Thank you for your suggestion!
I added an example notebook. https://github.com/okotaku/diffengine/tree/main/examples
Please check it;)
