### ISSUE TITLE
improve your readme

### ISSUE THREAD

**Issue by Ezra-Yu** [okotaku/diffengine#24]
The README is often one's first impression of a project; however, I was unable to quickly determine what your project does. This may be because I am not familiar with SD.

Maybe the following links can help you improve your readme.

[how to write good readme](https://dev.to/merlos/how-to-write-a-good-readme-bog)
[good examples](https://github.com/matiassingers/awesome-readme)

**Comment by okotaku** [comment]
@Ezra-Yu Thank you for your contribution! Those contents are really useful.

I created PR for this issue.
https://github.com/okotaku/diffengine/pull/26

Reviews or comments are welcomed;)
